### ISSUE TITLE
RequestDeduplicationMiddleware slows down crawl because requestDelay will affect even dropped Urls

### ISSUE THREAD

**Issue by osthafen** [roach-php/core#27]
Thank you for this great project!

I've got a little suggestion:

The requestDelay should only affect urls which aren't dropped. 
Otherwise these leads to a very long waiting time because there are a lot of duplicate URL scheduled when crawling a whole page.

Thank you!

**Comment by ksassnowski** [comment]
This will be fixed in the upcoming 1.0 release. The engine will keep scheduling requests until either the request queue is empty or the configured `concurrency` is reached before sending the requests. This means that requests that were dropped as part of the downloader middleware stack for any reason (not just duplicate requests) will not be affected by the request delay anymore.

**Comment by ksassnowski** [comment]
Fixed as part of the 1.0 release.
