### ISSUE TITLE
Xpath not working

### ISSUE THREAD

**Issue by Benoit1980** [roach-php/core#64]
Hello,

I was trying to test your library but cannot get a  basic xpath working on Google(as an example).
```
    public function parse(Response $response): Generator
    {
        $html = $response->filterXpath('//div[contains(@id, "center_col")]')->each(function (Crawler $node) {
            return $node->text();
        });
        yield $this->item([
            'html' => $html,
        ]);
    }
```

It returns and empty array and this is strange because there is a "<div class="s6JM6d" id="center_col"></div>" in the page.

Any idea why it is not working please?

Thank yyou.

**Comment by ksassnowski** [comment]
What URL were your crawling exactly? Because running the same XPath query on https://google.com in the browser console also doesn't return any results

**Comment by Benoit1980** [comment]
Hello,

Just a general result page on Google.

Thank you.

**Comment by ksassnowski** [comment]
That's because by default, Google displays the search result via Javascript. You can verify this by opening the search results page with Javascript disabled in your browser. You will get redirect to a static HTML version of the page after a few seconds.

So in order for this to work properly, you would have to use the [`ExecuteJavascriptMiddleware`](https://roach-php.dev/docs/downloader-middleware/#executing-javascript) in your spider. This isn't possible to do in the interactive shell though.

Also note that sometimes websites implement certain anti-scraping measures. So what you see in the browser and what your spider sees might not necessarily be the same thing.

**Comment by Benoit1980** [comment]
Thank you so much for the explanation.
